language: node_js
node_js:
  - "node"

scirpt_after: 
  - gitbook build
  - cd ./_book
  - git init
  - git config user.name ${USER.NAME}
  - git config user.email ${USER.EMAIL}
  - git add .
  - git commit -m "publish gitbook"
  - git push --force --quiet "https://${ACC_TOKEN}@${GH_REF}" master:${BRANCH}

branch:
  only:
    - master